name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cc65
      - name: Build
        run: make
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: brown2024.nes
