name: "godot-ci export"
on: push

env:
  EXPORT_NAME: brownvitro

jobs:
  export:
    name: Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/4.1.1.stable ~/.local/share/godot/export_templates/4.1.1.stable

      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --headless --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.EXPORT_NAME }}-windows
          path: build/windows/${{ env.EXPORT_NAME }}.exe
          if-no-files-found: error

      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot -v --headless --export-release "Linux/X11" build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.EXPORT_NAME }}-linux
          path: build/linux/${{ env.EXPORT_NAME }}.x86_64
          if-no-files-found: error

      - name: macOS Build
        run: |
          mkdir -v -p build/macos
          godot -v --headless --export-release "macOS" build/macos/$EXPORT_NAME.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.EXPORT_NAME }}-macos
          path: build/macos/${{ env.EXPORT_NAME }}.zip
          if-no-files-found: error
